/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pemilu.ui.auth;

import javax.swing.JOptionPane;
import pemilu.models.Admin;
import pemilu.models.Candidate;
import pemilu.models.User;
import pemilu.models.Voter;
import pemilu.services.DatabaseService;
import pemilu.ui.MainFrame;
import pemilu.ui.admin.AdminDashboard;
import pemilu.ui.candidate.CandidateDashboard;
import pemilu.ui.voter.VoterDashboard;

/**
 *
 * @author rakhacimano
 */
public class Login extends javax.swing.JPanel {

    private MainFrame mainFrame;
    public String loggedInUsername;

    public Login(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPage = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        labelPage.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 24)); // NOI18N
        labelPage.setForeground(new java.awt.Color(230, 230, 230));
        labelPage.setText("Login");

        labelUsername.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(230, 230, 230));
        labelUsername.setText("Username");

        inputUsername.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(230, 230, 230));

        labelPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(230, 230, 230));
        labelPassword.setText("Password");

        inputPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 12)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(230, 230, 230));

        btnLogin.setBackground(new java.awt.Color(0, 153, 204));
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(230, 230, 230));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(inputUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsername)
                            .addComponent(labelPage)
                            .addComponent(labelPassword))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelPage)
                .addGap(32, 32, 32)
                .addComponent(labelUsername)
                .addGap(8, 8, 8)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelPassword)
                .addGap(8, 8, 8)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = inputUsername.getText();
        String password = String.valueOf(inputPassword.getPassword());

        if (username.trim().isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Field harus diisi!");
            return;
        }

        User loggedInUser = DatabaseService.getUserByUsername(username);

        if (loggedInUser != null && loggedInUser.getPassword().equals(password)) {

            JOptionPane.showMessageDialog(this, "Login berhasil.");

            if (loggedInUser instanceof Admin) {
                mainFrame.showView(new AdminDashboard(mainFrame));
            } else if (loggedInUser instanceof Voter) {
                mainFrame.showView(new VoterDashboard(mainFrame, username)); // Mengirim username yang sedang login
            } else if (loggedInUser instanceof Candidate) {
                mainFrame.showView(new CandidateDashboard(mainFrame, username));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Login gagal. Username atau password salah.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel labelPage;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
